
-- 自動採番マスタ
CREATE TABLE MS_AUTO_NUMBER (
       SLIP_TYPE VARCHAR(2) NOT NULL
     , SLIP_YM VARCHAR(6) NOT NULL
     , LAST_SILP_NO DECIMAL(4) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (SLIP_TYPE, SLIP_YM)
)TYPE=InnoDB;

-- 取引先分類種別マスタ
CREATE TABLE MS_CATEGORY_TYPE (
       CATEGORY_TYPE_CODE VARCHAR(2) NOT NULL
     , CATE_TYPE_NAME VARCHAR(40)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CATEGORY_TYPE_CODE)
)TYPE=InnoDB;

-- 取引先グループマスタ
CREATE TABLE MS_COMPANY_GROUP (
       COMPANY_GROUP_CODE VARCHAR(4) NOT NULL
     , GROUP_NAME VARCHAR(40)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (COMPANY_GROUP_CODE)
)TYPE=InnoDB;

-- 部門マスタ
CREATE TABLE MS_DEPARTMENT (
       DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , DEPARTMENT_END_YMD VARCHAR(8)
     , DEPARTMENT_NAME VARCHAR(40)
     , LAYER DECIMAL(2) NOT NULL
     , UP_DEPARTMENT_CODE VARCHAR(5)
     , UP_DEPARTMENT_START_YMD VARCHAR(8)
     , SLIT_YN DECIMAL(1)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
)TYPE=InnoDB;

-- 出荷先マスタ
CREATE TABLE MS_DESTINATIONS (
       CUSTOMER_CODE VARCHAR(8) NOT NULL
     , CUSTOMER_SUB_NO DECIMAL(2) NOT NULL
     , DIST_NO DECIMAL(2) NOT NULL
     , DIST_NAME VARCHAR(40) NOT NULL
     , ZIP_CODE NCHAR(16)
     , ADDRESS1 VARCHAR(40)
     , ADDRESS2 VARCHAR(40)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CUSTOMER_CODE, CUSTOMER_SUB_NO, DIST_NO)
)TYPE=InnoDB;

-- 職種区分マスタ
CREATE TABLE MS_OCCUPATION (
       OCCU_CODE VARCHAR(2) NOT NULL
     , OCCU_NAME VARCHAR(40) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (OCCU_CODE)
)TYPE=InnoDB;

-- 商品分類マスタ
CREATE TABLE MS_PRODUCT_CATEGORY (
       CATEGORY_CODE VARCHAR(8) NOT NULL
     , PRODUCT_CATE_NAME VARCHAR(40)
     , LAYER DECIMAL(2) NOT NULL
     , UPPER_CATEGORY VARCHAR(8)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CATEGORY_CODE)
)TYPE=InnoDB;

-- 倉庫マスタ
CREATE TABLE MS_WAREHOUSE (
       WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , WAREHOUSE_NAME VARCHAR(40)
     , WAREHOUSE_TYPE VARCHAR(1)
     , ZIP_CODE NCHAR(16)
     , STATE VARCHAR(4)
     , ADDRESS1 VARCHAR(40)
     , ADDRESS2 VARCHAR(40)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (WAREHOUSE_CODE)
)TYPE=InnoDB;

-- 電子承認マスタ
CREATE TABLE MS_APPROVAL (
       APPROVAL_CODE VARCHAR(2) NOT NULL
     , APPROVAL_NAME VARCHAR(40)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (APPROVAL_CODE)
)TYPE=InnoDB;

-- 取引先マスタ
CREATE TABLE MS_COMPANYS (
       COMPANY_CODE VARCHAR(8) NOT NULL
     , COMPANY_NAME VARCHAR(40) NOT NULL
     , COMPANY_KANA VARCHAR(40)
     , SUP_TYPE DECIMAL(1)
     , ZIP_CODE NCHAR(16)
     , STATE VARCHAR(4)
     , ADDRESS1 VARCHAR(40)
     , ADDRESS2 VARCHAR(40)
     , NO_SALES_FLG DECIMAL(1)
     , WIDE_USE_TYPE DECIMAL(1)
     , COMPANY_GROUP_CODE VARCHAR(4) NOT NULL
     , MAX_CREDIT DECIMAL(10)
     , TEMP_CREDIT_UP DECIMAL(10)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (COMPANY_CODE)
)TYPE=InnoDB;

-- 取引先分類マスタ
CREATE TABLE MS_COMPANY_CATEGORY (
       CATEGORY_TYPE VARCHAR(2) NOT NULL
     , COMPANY_CATE_CODE VARCHAR(8) NOT NULL
     , COMPANY_CATE_NAME VARCHAR(40)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CATEGORY_TYPE, COMPANY_CATE_CODE)
)TYPE=InnoDB;

-- 社員マスタ
CREATE TABLE MS_EMPLOYEE (
       EMPLOYEE_CODE VARCHAR(10) NOT NULL
     , EMPLOYEE_NAME VARCHAR(40)
     , EMPLOYEE_KANA VARCHAR(40)
     , PASSWORD VARCHAR(8)
     , TEL VARCHAR(13)
     , FAX VARCHAR(13)
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , OCCU_CODE VARCHAR(2) NOT NULL
     , APPROVAL_CODE VARCHAR(2) NOT NULL
     , EMPLOYEE_PHOTO BLOB
     , EMPLOYEE_PROFILE TEXT
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (EMPLOYEE_CODE)
)TYPE=InnoDB;

-- 入金口座マスタ
CREATE TABLE MS_BANK_ACUT (
       BANK_ACUT_CODE VARCHAR(8) NOT NULL
     , RECIVE_ACT_NAME VARCHAR(40)
     , APPL_START_DATE DATE
     , APPL_END_DATE DATE
     , START_ACT_NAME VARCHAR(40)
     , RECIVE_BANK_ACT_TYPE VARCHAR(1)
     , RECIVE_ACT_NO VARCHAR(12)
     , BANK_ACT_TYPE VARCHAR(1)
     , ACT_NAME VARCHAR(40)
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , A_BANK_CODE VARCHAR(4)
     , A_BANK_BLNC_CODE VARCHAR(3)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (BANK_ACUT_CODE)
)TYPE=InnoDB;

-- 顧客マスタ
CREATE TABLE MS_CUSTOMERS (
       CUSTOMER_CODE VARCHAR(8) NOT NULL
     , CUSTOMER_SUB_NO DECIMAL(2) NOT NULL
     , CUSTOMER_TYPE DECIMAL(1)
     , AR_CODE VARCHAR(8) NOT NULL
     , AR_SUB_NO DECIMAL(2)
     , PAYER_CODE VARCHAR(8) NOT NULL
     , PAYER_SUB_NO DECIMAL(2)
     , CUSTOMER_NAME VARCHAR(40) NOT NULL
     , CUSTOMER_KANA VARCHAR(40)
     , EMPLOYEE_CODE VARCHAR(10) NOT NULL
     , CUSTOMER_USER_NAME VARCHAR(40)
     , CUSTOMER_USER_DEP_NAME VARCHAR(40)
     , CUSTOMER_ZIP_CODE NCHAR(16)
     , CUSTOMER_STATE VARCHAR(4)
     , CUSTOMER_ADDRESS1 VARCHAR(40)
     , CUSTOMER_ADDRESS2 VARCHAR(40)
     , CUSTOMER_TEL VARCHAR(13)
     , CUSTOMER_FAX VARCHAR(13)
     , CUSTOMER_EMAIL VARCHAR(100)
     , CUSTOMER_AR_FLAG DECIMAL(1)
     , CUSTOMER_CLOSE_DATE1 DECIMAL(2) NOT NULL
     , CUSTOMER_PAY_MONTHS1 DECIMAL(1)
     , CUSTOMER_PAY_DATES1 DECIMAL(1)
     , CUSTOMER_PAY_METHOD1 DECIMAL(1)
     , CUSTOMER_CLOSE_DATE2 DECIMAL(2) NOT NULL
     , CUSTOMER_PAY_MONTHS2 DECIMAL(1)
     , CUSTOMER_PAY_DATES2 DECIMAL(1)
     , CUSTOMER_PAY_METHOD2 DECIMAL(1)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CUSTOMER_CODE, CUSTOMER_SUB_NO)
)TYPE=InnoDB;

-- 受注データ
CREATE TABLE TR_RECEIVE_ORDERS (
       RECEIVE_ORDER_NO VARCHAR(10) NOT NULL
     , ORDER_DATE DATE NOT NULL
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , CUSTOMER_CODE VARCHAR(8) NOT NULL
     , CUSTOMER_SUB_NO DECIMAL(2)
     , EMPLOYEE_CODE VARCHAR(10) NOT NULL
     , REQUIRED_DATE DATE
     , CUSTOMER_RECEIVE_ORDER_NO VARCHAR(10)
     , WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , RECEIVE_ORDER_AMNT DECIMAL(10) NOT NULL
     , CMP_TAX DECIMAL(10) NOT NULL
     , SLIP_COMMENT VARCHAR(1000)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (RECEIVE_ORDER_NO)
)TYPE=InnoDB;

-- 商品マスタ
CREATE TABLE MS_PRODUCTS (
       PRODUCT_CODE VARCHAR(16) NOT NULL
     , PRODUCT_FULLNAME VARCHAR(40) NOT NULL
     , PRODUCT_NAME VARCHAR(40) NOT NULL
     , PRODUCT_KANA VARCHAR(40) NOT NULL
     , PRODUCT_TYPE VARCHAR(1)
     , SERIAL_NO VARCHAR(40)
     , UNITPRICE DECIMAL(8) NOT NULL
     , SEND_ORDER_PRICE DECIMAL(8)
     , COST DECIMAL(8) NOT NULL
     , TAX_TYPE DECIMAL(1) NOT NULL
     , CATEGORY_CODE VARCHAR(8)
     , WIDE_USE_TYPE DECIMAL(1)
     , STOCK_MANAGE_TYPE DECIMAL(1)
     , STOCK_RESERVE_TYPE DECIMAL(1)
     , SUP_CODE VARCHAR(8) NOT NULL
     , SUP_SUB_NO DECIMAL(2)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (PRODUCT_CODE)
)TYPE=InnoDB;

-- 仕入先マスタ
CREATE TABLE MS_SUPPLIER (
       SUP_CODE VARCHAR(8) NOT NULL
     , SUP_SUB_NO DECIMAL(2) NOT NULL
     , SUP_NAME VARCHAR(40) NOT NULL
     , SUP_KANA VARCHAR(40)
     , SUP_EMPLOYEE_NAME VARCHAR(40)
     , SUP_DEP_NAME VARCHAR(40)
     , SUP_ZIP_CODE NCHAR(16)
     , SUP_STATE VARCHAR(4)
     , SUP_ADDRESS1 VARCHAR(40)
     , SUP_ADDRESS2 VARCHAR(40)
     , SUP_TEL VARCHAR(13)
     , SUP_FAX VARCHAR(13)
     , SUP_EMAIL VARCHAR(100)
     , SUP_CLOSE_DATE DECIMAL(2) NOT NULL
     , SUP_PAY_MONTHS DECIMAL(1)
     , SUP_PAY_DATES DECIMAL(1)
     , PAY_METHOD_TYPE DECIMAL(1)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (SUP_CODE, SUP_SUB_NO)
)TYPE=InnoDB;

-- 請求データ
CREATE TABLE TR_INVOICE (
       INVOICE_NO VARCHAR(10) NOT NULL
     , INVOICED_DATE DATE
     , COMPANY_CODE VARCHAR(8) NOT NULL
     , CUSTOMER_SUB_NO DECIMAL(2)
     , LAST_RECEIVED DECIMAL(13)
     , MONTH_SALES DECIMAL(13)
     , MONTH_RECEIVED DECIMAL(13)
     , MONTH_INVOICE DECIMAL(13)
     , CMP_TAX DECIMAL(10) NOT NULL
     , INVOICE_RECEIVED DECIMAL(13)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (INVOICE_NO)
)TYPE=InnoDB;

-- 発注データ
CREATE TABLE TR_SEND_ORDERS (
       SEND_ORDER_NO VARCHAR(10) NOT NULL
     , SEND_ORDER_DATE DATE
     , RECEIVE_ORDER_NO VARCHAR(10) NOT NULL
     , SUP_CODE VARCHAR(8) NOT NULL
     , SUP_SUB_NO DECIMAL(2)
     , EMPLOYEE_CODE VARCHAR(10) NOT NULL
     , DUE_DATE DATE
     , WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , SEND_ORDER_AMNT DECIMAL(10)
     , CMP_TAX DECIMAL(10) NOT NULL
     , SLIP_COMMENT VARCHAR(1000)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (SEND_ORDER_NO)
)TYPE=InnoDB;

-- 仕入データ
CREATE TABLE TR_PURCHASE (
       PURCHASE_NO VARCHAR(10) NOT NULL
     , PURCHASE_DATE DATE
     , SUP_CODE VARCHAR(8) NOT NULL
     , SUP_SUB_NO DECIMAL(2)
     , EMPLOYEE_CODE VARCHAR(10) NOT NULL
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , SEND_ORDER_NO VARCHAR(10)
     , PURCHASE_AMMOUNT DECIMAL(10)
     , CMP_TAX DECIMAL(10) NOT NULL
     , SLIP_COMMENT VARCHAR(1000)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (PURCHASE_NO)
)TYPE=InnoDB;

-- 売上データ
CREATE TABLE TR_SALES (
       SALES_NO VARCHAR(10) NOT NULL
     , RECEIVE_ORDER_NO VARCHAR(10) NOT NULL
     , SALES_DATE DATE NOT NULL
     , SALES_TYPE DECIMAL(1)
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , COMPANY_CODE VARCHAR(8) NOT NULL
     , EMPLOYEE_CODE VARCHAR(10) NOT NULL
     , SALES_AMNT DECIMAL(13) NOT NULL
     , CMP_TAX DECIMAL(10) NOT NULL
     , SLIP_COMMENT VARCHAR(1000)
     , UPDATED_NO DECIMAL(10)
     , ORGNL_NO VARCHAR(10)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (SALES_NO)
)TYPE=InnoDB;

-- 部品表マスタ
CREATE TABLE MS_BOM (
       PRODUCT_CODE VARCHAR(16) NOT NULL
     , BOM_CODE VARCHAR(16) NOT NULL
     , QUANTITY DECIMAL(4) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (BOM_CODE, PRODUCT_CODE)
)TYPE=InnoDB;

-- 取引先分類所属マスタ
CREATE TABLE MS_COMPANY_CATEGORY_GROUP (
       CATEGORY_TYPE VARCHAR(2) NOT NULL
     , COMPANY_CATE_CODE VARCHAR(8) NOT NULL
     , COMPANY_CODE VARCHAR(8) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CATEGORY_TYPE, COMPANY_CATE_CODE, COMPANY_CODE)
)TYPE=InnoDB;

-- 入金データ
CREATE TABLE TR_CREDIT (
       CREDIT_NO VARCHAR(10) NOT NULL
     , CREDIT_DATE DATE
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , CUSTOMER_CODE VARCHAR(8) NOT NULL
     , CUSTOMER_SUB_NO DECIMAL(2)
     , PAY_METHOD_TYPE DECIMAL(1)
     , BANK_ACUT_CODE VARCHAR(8)
     , RECEIVED_AMNT DECIMAL(13)
     , RECEIVED DECIMAL(13)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (CREDIT_NO)
)TYPE=InnoDB;

-- 与信残高データ
CREATE TABLE TR_CREDIT_BALANCE (
       COMPANY_CODE VARCHAR(8) NOT NULL
     , ORDER_BALANCE DECIMAL(13)
     , REC_BALANCE DECIMAL(13)
     , PAY_BALANCE DECIMAL(13)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (COMPANY_CODE)
)TYPE=InnoDB;

-- 請求データ明細
CREATE TABLE TR_INVOICE_DATAILS (
       INVOICE_NO VARCHAR(10) NOT NULL
     , SALES_NO VARCHAR(10) NOT NULL
     , ROW_NO DECIMAL(3) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (INVOICE_NO, ROW_NO, SALES_NO)
)TYPE=InnoDB;

-- 棚番マスタ
CREATE TABLE MS_LOCATION (
       WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , LOCATION_CODE VARCHAR(4) NOT NULL
     , PRODUCT_CODE VARCHAR(16) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (WAREHOUSE_CODE, LOCATION_CODE, PRODUCT_CODE)
)TYPE=InnoDB;

-- 受注データ明細
CREATE TABLE TR_RECEIVE_ORDER_DETAILS (
       RECEIVE_ORDER_NO VARCHAR(10) NOT NULL
     , SO_ROW_NO DECIMAL(3) NOT NULL
     , PRODUCT_CODE VARCHAR(16) NOT NULL
     , PRODUCT_NAME VARCHAR(40) NOT NULL
     , UNITPRICE DECIMAL(8) NOT NULL
     , QUANTITY DECIMAL(4) NOT NULL
     , CMP_TAX_RATE DECIMAL(3)
     , RESERVE_QTY DECIMAL(4)
     , DELIVERY_ORDER_QTY DECIMAL(4)
     , DELIVERED_QTY DECIMAL(4)
     , COMPLETE_FLG DECIMAL(1) NOT NULL
     , DISCOUNT DECIMAL(4) NOT NULL
     , DELIVERY_DATE DATE
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (RECEIVE_ORDER_NO, SO_ROW_NO)
)TYPE=InnoDB;

-- 支払データ
CREATE TABLE TR_PAY (
       PAY_NO VARCHAR(10) NOT NULL
     , PAY_DATE DECIMAL(1)
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , SUP_CODE VARCHAR(8) NOT NULL
     , SUP_SUB_NO DECIMAL(2)
     , PAY_METHOD_TYPE DECIMAL(1)
     , PAY_AMNT DECIMAL(13)
     , CMP_TAX DECIMAL(10) NOT NULL
     , COMPLETE_FLG DECIMAL(1) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (PAY_NO)
)TYPE=InnoDB;

-- 発注データ明細
CREATE TABLE TR_SEND_ORDER_DETAILS (
       SEND_ORDER_NO VARCHAR(10) NOT NULL
     , SEND_ORDER_ROW_NO DECIMAL(3) NOT NULL
     , SEND_ORDER_ROW_DSP_NO DECIMAL(3) NOT NULL
     , RECEIVE_ORDER_NO VARCHAR(10) NOT NULL
     , SO_ROW_NO DECIMAL(3) NOT NULL
     , PRODUCT_CODE VARCHAR(16) NOT NULL
     , PRODUCT_NAME VARCHAR(40) NOT NULL
     , SEND_ORDER_PRICE DECIMAL(8)
     , SEND_ORDER_QT DECIMAL(4) NOT NULL
     , RECIVED_QT DECIMAL(4) NOT NULL
     , COMPLETE_FLG DECIMAL(1) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (SEND_ORDER_NO, SEND_ORDER_ROW_NO)
)TYPE=InnoDB;

-- 顧客別販売単価
CREATE TABLE MS_PRICE_BY_CUSTOMER (
       PRODUCT_CODE VARCHAR(16) NOT NULL
     , COMPANY_CODE VARCHAR(8) NOT NULL
     , UNITPRICE DECIMAL(8) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (COMPANY_CODE, PRODUCT_CODE)
)TYPE=InnoDB;

-- 仕入データ明細
CREATE TABLE TR_PURCHASE_DETAILS (
       PURCHASE_NO VARCHAR(10) NOT NULL
     , PURCHASE_ROW_NO DECIMAL(3) NOT NULL
     , PURCHASE_ROW_DSP_NO DECIMAL(3) NOT NULL
     , SEND_ORDER_ROW_NO DECIMAL(3) NOT NULL
     , PRODUCT_CODE VARCHAR(16) NOT NULL
     , WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , PRODUCT_NAME VARCHAR(40) NOT NULL
     , SEND_ORDER_PRICE DECIMAL(8)
     , PURCHASE_QUANTITY DECIMAL(4) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (PURCHASE_NO, PURCHASE_ROW_NO)
)TYPE=InnoDB;

-- 売上データ明細
CREATE TABLE TR_SALES_DETAILS (
       SALES_NO VARCHAR(10) NOT NULL
     , ROW_NO DECIMAL(3) NOT NULL
     , PRODUCT_CODE VARCHAR(16) NOT NULL
     , PRODUCT_NAME VARCHAR(40) NOT NULL
     , UNITPRICE DECIMAL(8) NOT NULL
     , DELIVERED_QTY DECIMAL(4)
     , QUANTITY DECIMAL(4) NOT NULL
     , DISCOUNT DECIMAL(4) NOT NULL
     , INVOICED_DATE DATE
     , INVOICE_NO VARCHAR(10)
     , INVOICE_DELAY_TYPE DECIMAL(1)
     , AUTO_JOURNAL_DATE DATE
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (ROW_NO, SALES_NO)
)TYPE=InnoDB;

-- 在庫データ
CREATE TABLE TR_STOCK (
       WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , PRODUCT_CODE VARCHAR(16) NOT NULL
     , ROT_NO VARCHAR(20) NOT NULL
     , STOCK_TYPE VARCHAR(1) NOT NULL
     , QUALITY_TYPE VARCHAR(1) NOT NULL
     , ACTUAL DECIMAL(4) NOT NULL
     , VALID DECIMAL(4) NOT NULL
     , LAST_DELIVERY_DATE DATE
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (PRODUCT_CODE, QUALITY_TYPE, ROT_NO, STOCK_TYPE, WAREHOUSE_CODE)
)TYPE=InnoDB;

-- 倉庫部門マスタ
CREATE TABLE MS_WAREHOUSE_DEPARTMENT (
       WAREHOUSE_CODE VARCHAR(8) NOT NULL
     , DEPARTMENT_CODE VARCHAR(5) NOT NULL
     , DEPARTMENT_START_YMD VARCHAR(8) NOT NULL
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (WAREHOUSE_CODE, DEPARTMENT_CODE, DEPARTMENT_START_YMD)
)TYPE=InnoDB;

-- 代替商品
CREATE TABLE MS_ALTERNATE_PRODUCTS (
       PRODUCT_CODE VARCHAR(16) NOT NULL
     , ALT_PRODUCT_CODE VARCHAR(16) NOT NULL
     , PRIORITY DECIMAL(2)
     , UPDATE_DATE TIMESTAMP NOT NULL
     , UPDATER VARCHAR(12) NOT NULL
     , PRIMARY KEY (ALT_PRODUCT_CODE, PRODUCT_CODE)
)TYPE=InnoDB;

ALTER TABLE MS_COMPANYS
  ADD CONSTRAINT FK_MS_COMPANYS_COMPANY_GROUP_CODE
      FOREIGN KEY (COMPANY_GROUP_CODE)
      REFERENCES MS_COMPANY_GROUP (COMPANY_GROUP_CODE);

ALTER TABLE MS_COMPANY_CATEGORY
  ADD CONSTRAINT FK_MS_COMPANY_CATEGORY_CATEGORY_TYPE
      FOREIGN KEY (CATEGORY_TYPE)
      REFERENCES MS_CATEGORY_TYPE (CATEGORY_TYPE_CODE);

ALTER TABLE MS_DEPARTMENT
  ADD CONSTRAINT FK_MS_DEPARTMENT_UP_DEPARTMENT_CODE
      FOREIGN KEY (UP_DEPARTMENT_CODE, UP_DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE MS_DESTINATIONS
  ADD CONSTRAINT FK_MS_DESTINATIONS_CUSTOMER_CODE
      FOREIGN KEY (CUSTOMER_CODE, CUSTOMER_SUB_NO)
      REFERENCES MS_CUSTOMERS (CUSTOMER_CODE, CUSTOMER_SUB_NO);

ALTER TABLE MS_EMPLOYEE
  ADD CONSTRAINT FK_MS_EMPLOYEE_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE MS_EMPLOYEE
  ADD CONSTRAINT FK_MS_EMPLOYEE_OCCU_CODE
      FOREIGN KEY (OCCU_CODE)
      REFERENCES MS_OCCUPATION (OCCU_CODE);

ALTER TABLE MS_EMPLOYEE
  ADD CONSTRAINT FK_MS_EMPLOYEE_APPROVAL_CODE
      FOREIGN KEY (APPROVAL_CODE)
      REFERENCES MS_APPROVAL (APPROVAL_CODE);

ALTER TABLE MS_BANK_ACUT
  ADD CONSTRAINT FK_MS_BANK_ACUT_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE MS_CUSTOMERS
  ADD CONSTRAINT FK_MS_CUSTOMERS_CUSTOMER_CODE
      FOREIGN KEY (CUSTOMER_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE MS_CUSTOMERS
  ADD CONSTRAINT FK_MS_CUSTOMERS_EMPLOYEE_CODE
      FOREIGN KEY (EMPLOYEE_CODE)
      REFERENCES MS_EMPLOYEE (EMPLOYEE_CODE);

ALTER TABLE MS_CUSTOMERS
  ADD CONSTRAINT FK_MS_CUSTOMERS_AR_CODE
      FOREIGN KEY (AR_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE MS_CUSTOMERS
  ADD CONSTRAINT FK_MS_CUSTOMERS_PAYER_CODE
      FOREIGN KEY (PAYER_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE TR_RECEIVE_ORDERS
  ADD CONSTRAINT FK_TR_RECEIVE_ORDERS_CUSTOMER_CODE
      FOREIGN KEY (CUSTOMER_CODE, CUSTOMER_SUB_NO)
      REFERENCES MS_CUSTOMERS (CUSTOMER_CODE, CUSTOMER_SUB_NO);

ALTER TABLE TR_RECEIVE_ORDERS
  ADD CONSTRAINT FK_TR_RECEIVE_ORDERS_EMPLOYEE_CODE
      FOREIGN KEY (EMPLOYEE_CODE)
      REFERENCES MS_EMPLOYEE (EMPLOYEE_CODE);

ALTER TABLE TR_RECEIVE_ORDERS
  ADD CONSTRAINT FK_TR_RECEIVE_ORDERS_WAREHOUSE_CODE
      FOREIGN KEY (WAREHOUSE_CODE)
      REFERENCES MS_WAREHOUSE (WAREHOUSE_CODE);

ALTER TABLE TR_RECEIVE_ORDERS
  ADD CONSTRAINT FK_TR_RECEIVE_ORDERS_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE MS_PRODUCTS
  ADD CONSTRAINT FK_MS_PRODUCT_CATEGORY_CODE
      FOREIGN KEY (CATEGORY_CODE)
      REFERENCES MS_PRODUCT_CATEGORY (CATEGORY_CODE);

ALTER TABLE MS_PRODUCT_CATEGORY
  ADD CONSTRAINT FK_MS_PRODUCT_CATEGORY_UPPER_CATEGORY
      FOREIGN KEY (UPPER_CATEGORY)
      REFERENCES MS_PRODUCT_CATEGORY (CATEGORY_CODE);

ALTER TABLE MS_SUPPLIER
  ADD CONSTRAINT FK_MS_SUPPLIER_SUP_CODE
      FOREIGN KEY (SUP_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE TR_INVOICE
  ADD CONSTRAINT FK_TR_INVOICE_COMPANY_CODE
      FOREIGN KEY (COMPANY_CODE, CUSTOMER_SUB_NO)
      REFERENCES MS_CUSTOMERS (CUSTOMER_CODE, CUSTOMER_SUB_NO);

ALTER TABLE TR_SEND_ORDERS
  ADD CONSTRAINT FK_TR_SEND_ORDERS_EMPLOYEE_CODE
      FOREIGN KEY (EMPLOYEE_CODE)
      REFERENCES MS_EMPLOYEE (EMPLOYEE_CODE);

ALTER TABLE TR_SEND_ORDERS
  ADD CONSTRAINT FK_TR_SEND_ORDERS_SUP_CODE
      FOREIGN KEY (SUP_CODE, SUP_SUB_NO)
      REFERENCES MS_SUPPLIER (SUP_CODE, SUP_SUB_NO);

ALTER TABLE TR_SEND_ORDERS
  ADD CONSTRAINT FK_TR_SEND_ORDERS_RECEIVE_ORDER_NO
      FOREIGN KEY (RECEIVE_ORDER_NO)
      REFERENCES TR_RECEIVE_ORDERS (RECEIVE_ORDER_NO);

ALTER TABLE TR_SEND_ORDERS
  ADD CONSTRAINT FK_TR_SEND_ORDERS_WAREHOUSE_CODE
      FOREIGN KEY (WAREHOUSE_CODE)
      REFERENCES MS_WAREHOUSE (WAREHOUSE_CODE);

ALTER TABLE TR_PURCHASE
  ADD CONSTRAINT FK_TR_PURCHASE_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE TR_PURCHASE
  ADD CONSTRAINT FK_TR_PURCHASE_EMPLOYEE_CODE
      FOREIGN KEY (EMPLOYEE_CODE)
      REFERENCES MS_EMPLOYEE (EMPLOYEE_CODE);

ALTER TABLE TR_PURCHASE
  ADD CONSTRAINT FK_TR_PURCHASE_SUP_CODE
      FOREIGN KEY (SUP_CODE, SUP_SUB_NO)
      REFERENCES MS_SUPPLIER (SUP_CODE, SUP_SUB_NO);

ALTER TABLE TR_PURCHASE
  ADD CONSTRAINT FK_TR_PURCHASE_SEND_ORDER_NO
      FOREIGN KEY (SEND_ORDER_NO)
      REFERENCES TR_SEND_ORDERS (SEND_ORDER_NO);

ALTER TABLE TR_SALES
  ADD CONSTRAINT FK_TR_SALES_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE TR_SALES
  ADD CONSTRAINT FK_TR_SALES_EMPLOYEE_CODE
      FOREIGN KEY (EMPLOYEE_CODE)
      REFERENCES MS_EMPLOYEE (EMPLOYEE_CODE);

ALTER TABLE TR_SALES
  ADD CONSTRAINT FK_TR_SALES_COMPANY_CODE
      FOREIGN KEY (COMPANY_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE TR_SALES
  ADD CONSTRAINT FK_TR_SALES_RECEIVE_ORDER_NO
      FOREIGN KEY (RECEIVE_ORDER_NO)
      REFERENCES TR_RECEIVE_ORDERS (RECEIVE_ORDER_NO);

ALTER TABLE MS_BOM
  ADD CONSTRAINT FK_MS_BOM_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE MS_BOM
  ADD CONSTRAINT FK_MS_BOM_BOM_CODE
      FOREIGN KEY (BOM_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE MS_COMPANY_CATEGORY_GROUP
  ADD CONSTRAINT FK_MS_COMPANY_CATEGORY_GROUP_CATEGORY_TYPE
      FOREIGN KEY (CATEGORY_TYPE, COMPANY_CATE_CODE)
      REFERENCES MS_COMPANY_CATEGORY (CATEGORY_TYPE, COMPANY_CATE_CODE);

ALTER TABLE MS_COMPANY_CATEGORY_GROUP
  ADD CONSTRAINT FK_MS_COMPANY_CATEGORY_GROUP_COMPANY_CODE
      FOREIGN KEY (COMPANY_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE TR_CREDIT
  ADD CONSTRAINT FK_TR_CREDIT_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE TR_CREDIT
  ADD CONSTRAINT FK_TR_CREDIT_BANK_ACUT_CODE
      FOREIGN KEY (BANK_ACUT_CODE)
      REFERENCES MS_BANK_ACUT (BANK_ACUT_CODE);

ALTER TABLE TR_CREDIT
  ADD CONSTRAINT FK_TR_CREDIT_COMPANY_CODE
      FOREIGN KEY (COMPANY_CODE, COMPANY_SUB_NO)
      REFERENCES MS_CUSTOMERS (CUSTOMER_CODE, CUSTOMER_SUB_NO);

ALTER TABLE TR_CREDIT_BALANCE
  ADD CONSTRAINT FK_TR_CREDIT_BALANCE_COMPANY_CODE
      FOREIGN KEY (COMPANY_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE TR_INVOICE_DATAILS
  ADD CONSTRAINT FK_TR_INVOICE_DATAILS_INVOICE_NO
      FOREIGN KEY (INVOICE_NO)
      REFERENCES TR_INVOICE (INVOICE_NO);

ALTER TABLE MS_LOCATION
  ADD CONSTRAINT FK_MS_LOCATION_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE MS_LOCATION
  ADD CONSTRAINT FK_MS_LOCATION_WAREHOUSE_CODE
      FOREIGN KEY (WAREHOUSE_CODE)
      REFERENCES MS_WAREHOUSE (WAREHOUSE_CODE);

ALTER TABLE TR_RECEIVE_ORDER_DETAILS
  ADD CONSTRAINT FK_TR_RECEIVE_ORDER_DETAILS_RECEIVE_ORDER_NO
      FOREIGN KEY (RECEIVE_ORDER_NO)
      REFERENCES TR_RECEIVE_ORDERS (RECEIVE_ORDER_NO);

ALTER TABLE TR_RECEIVE_ORDER_DETAILS
  ADD CONSTRAINT FK_TR_RECEIVE_ORDER_DETAILS_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE TR_PAY
  ADD CONSTRAINT FK_TR_PAY_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE TR_PAY
  ADD CONSTRAINT FK_TR_PAY_SUP_CODE
      FOREIGN KEY (SUP_CODE, SUP_SUB_NO)
      REFERENCES MS_SUPPLIER (SUP_CODE, SUP_SUB_NO);

ALTER TABLE TR_SEND_ORDER_DETAILS
  ADD CONSTRAINT FK_TR_SEND_ORDER_DETAILS_SEND_ORDER_NO
      FOREIGN KEY (SEND_ORDER_NO)
      REFERENCES TR_SEND_ORDERS (SEND_ORDER_NO);

ALTER TABLE TR_SEND_ORDER_DETAILS
  ADD CONSTRAINT FK_TR_SEND_ORDER_DETAILS_RECEIVE_ORDER_NO
      FOREIGN KEY (RECEIVE_ORDER_NO)
      REFERENCES TR_RECEIVE_ORDERS (RECEIVE_ORDER_NO);

ALTER TABLE TR_SEND_ORDER_DETAILS
  ADD CONSTRAINT FK_TR_SEND_ORDER_DETAILS_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE MS_PRICE_BY_CUSTOMER
  ADD CONSTRAINT FK_MS_PRICE_BY_CUSTOMER_COMPANY_CODE
      FOREIGN KEY (COMPANY_CODE)
      REFERENCES MS_COMPANYS (COMPANY_CODE);

ALTER TABLE MS_PRICE_BY_CUSTOMER
  ADD CONSTRAINT FK_MS_PRICE_BY_CUSTOMER_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE TR_PURCHASE_DETAILS
  ADD CONSTRAINT FK_TR_PURCHASE_DETAILS_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE TR_PURCHASE_DETAILS
  ADD CONSTRAINT FK_TR_PURCHASE_DETAILS_PURCHASE_NO
      FOREIGN KEY (PURCHASE_NO)
      REFERENCES TR_PURCHASE (PURCHASE_NO);

ALTER TABLE TR_PURCHASE_DETAILS
  ADD CONSTRAINT FK_TR_PURCHASE_DETAILS_WAREHOUSE_CODE
      FOREIGN KEY (WAREHOUSE_CODE)
      REFERENCES MS_WAREHOUSE (WAREHOUSE_CODE);

ALTER TABLE TR_SALES_DETAILS
  ADD CONSTRAINT FK_TR_SALES_DETAILS_SALES_NO
      FOREIGN KEY (SALES_NO)
      REFERENCES TR_SALES (SALES_NO);

ALTER TABLE TR_SALES_DETAILS
  ADD CONSTRAINT FK_TR_SALES_DETAILS_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE TR_STOCK
  ADD CONSTRAINT FK_TR_STOCK_WAREHOUSE_CODE
      FOREIGN KEY (WAREHOUSE_CODE)
      REFERENCES MS_WAREHOUSE (WAREHOUSE_CODE);

ALTER TABLE TR_STOCK
  ADD CONSTRAINT FK_TR_STOCK_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE MS_WAREHOUSE_DEPARTMENT
  ADD CONSTRAINT FK_MS_WAREHOUSE_DEPARTMENT_DEPARTMENT_CODE
      FOREIGN KEY (DEPARTMENT_CODE, DEPARTMENT_START_YMD)
      REFERENCES MS_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_START_YMD);

ALTER TABLE MS_WAREHOUSE_DEPARTMENT
  ADD CONSTRAINT FK_MS_WAREHOUSE_DEPARTMENT_WAREHOUSE_CODE
      FOREIGN KEY (WAREHOUSE_CODE)
      REFERENCES MS_WAREHOUSE (WAREHOUSE_CODE);

ALTER TABLE MS_ALTERNATE_PRODUCTS
  ADD CONSTRAINT FK_MS_ALTERNATE_PRODUCTS_PRODUCT_CODE
      FOREIGN KEY (PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

ALTER TABLE MS_ALTERNATE_PRODUCTS
  ADD CONSTRAINT FK_MS_ALTERNATE_PRODUCTS_ALT_PRODUCT_CODE
      FOREIGN KEY (ALT_PRODUCT_CODE)
      REFERENCES MS_PRODUCTS (PRODUCT_CODE);

